---
app:
  name: "Print Shop Service"
  version: v0.0.0 # auto detection
  environment: local # local, dev, test, prod

debugging:
  debug: true
  unexpected_http_status: 418 # http.StatusTeapot
  error_caller:
    enable: true
    depth: 3
    show_func_name: true
    upper_bounds:
      - github.com/mondegor/go-sysmess/mrerr.(*ProtoAppError).New
      - github.com/mondegor/go-sysmess/mrerr.(*ProtoAppError).Wrap
      - github.com/mondegor/go-webcore/mrcore.PrepareError
      - github.com/mondegor/go-webcore/mrcore/mrapp.(*ErrorHandler).Perform
      - github.com/mondegor/go-webcore/mrcore/mrapp.(*ErrorHandler).PerformWithCommit
      - github.com/mondegor/go-webcore/mrlog/zerolog.(*eventAdapter).Err
      - github.com/mondegor/go-storage/mrpostgres.(*ConnAdapter).begin
      - github.com/mondegor/go-storage/mrpostgres.(*ConnAdapter).Exec
      - github.com/mondegor/go-storage/mrpostgres.(*ConnAdapter).Query
      - github.com/mondegor/go-storage/mrpostgres.(*queryRow).Scan
      - github.com/mondegor/go-storage/mrpostgres.(*queryRows).Err
      - github.com/mondegor/go-storage/mrpostgres.(*queryRows).Scan
      - github.com/mondegor/go-storage/mrpostgres.(*transaction).Exec

logger:
  level: trace # info, warn, error, fatal, debug, trace
  timestamp_format: TimeOnly # RFC3339, RFC3339Nano, DateTime, TimeOnly
  json_format: false
  console_color: true

sentry:
  # dsn: http://id@127.0.0.1:9980/1
  traces_sample_rate: 1.0
  flush_timeout: 2s

servers:
  rest_server:
    read_timeout: 3s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8080
  internal_server:
    read_timeout: 3s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8084

storage:
  type: postgres
  host: db-postgres
  port: 5432
  username: user_pg
  password: 123456
  database: db_pg
  migrations_dir: "./migrations" # if empty automatic migration will be disabled
  migrations_table: print_shop_migrations
  max_pool_size: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 15m
  timeout: 60s

redis:
  host: db-redis
  port: 6379
  password: 123456
  read_timeout: 15s
  write_timeout: 15s

file_system:
  dir_mode: 0775
  create_dirs: true # check and create if not exists

file_providers:
  image_storage:
    name: imageStorage
    root_dir: "../img"

cors:
  allowed_origins:
    - http://print-shop.local
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Correlation-Id
    - X-Idempotency-Key
  exposed_headers:
    - X-Request-Id
  allow_credentials: true

translation:
  dir_path: "./translate"
  lang_codes: # the first language is default
    - en_EN
    - ru_RU
  dictionaries:
    dir_path: "./translate/dict"
    list:
      - catalog/boxes
      - catalog/laminates
      - catalog/papers
      - dictionaries/material-types
      - dictionaries/paper-colors
      - dictionaries/paper-factures
      - dictionaries/print-formats

senders:
  mail:
    # default_from: PrintShop <username@yandex.ru>
    # smtp_host: smtp.yandex.ru
    # smtp_port: 587 # STARTTLS
    # smtp_user_name: username
    # smtp_password: password
  telegram_bot:
    # name: "@Telegram_Bot"
    # token: "0000000000:AAAaaAAaaAAaaAAAA0AAaaaaAaAAAAAAa_a"

app_sections:
  admin_api:
    privilege: apiAdm
    auth:
      secret: "The secret for symmetric security key"
      audience: "127.0.0.1:80"
  providers_api:
    privilege: apiProv
    auth:
      secret: "The secret for symmetric security key"
      audience: "127.0.0.1:80"
  public_api:
    privilege: apiPub
    auth:
      secret: "The secret for symmetric security key"
      audience: "127.0.0.1:80"

access_control:
  roles:
    dir_path: "./roles"
    file_type: yaml
    list: # the first role is the guest role
      - guests
      - administrators
      - providers
  privileges:
    - apiAdm
    - apiProv
    - apiPub
  permissions:
    - modCalculationsAlgo
    - modCalculationsBox
    - modCalculationsQueryHistory
    - modCatalogBox
    - modCatalogPaper
    - modCatalogLaminate
    - modControlsElementTemplate
    - modControlsSubmitForm
    - modControlsSubmitFormToPublish
    - modDictionariesMaterialType
    - modDictionariesPaperColor
    - modDictionariesPaperFacture
    - modDictionariesPrintFormat
    - modFileStation
    - modProviderAccounts

modules_settings:
  general:
    page_size_max: 1000
    page_size_default: 50
  provider_account:
    company_page_logo:
      file_provider: imageStorage # file_providers.image_storage
  file_station:
    image_proxy:
      host: http://print-shop.local
      base_path: /img/{{path}}
      file_provider: imageStorage # file_providers.image_storage

validation:
  files:
    json:
      min_size: 1 # 1b
      max_size: 524288 # 512Kb
      max_files: 4
      check_request_content_type: true
      extensions:
        - json

  images:
    logo:
      max_width: 1920 # pixels
      max_height: 1080 # pixels
      check_body: true
      file:
        min_size: 512 # 512b
        max_size: 131072 # 128Kb
        max_files: 4
        check_request_content_type: true
        extensions:
          - jpeg
          - jpg
          - png

  mime_types:
    - type: "application/octet-stream"
      ext: psd
    - type: "application/pdf"
      ext: pdf
    - type: "application/json"
      ext: json
    - type: "application/x-tar"
      ext: tgz
    - type: "application/zip"
      ext: zip
    - type: "image/gif"
      ext: gif
    - type: "image/jpeg"
      ext: jpeg
    - type: "image/jpeg"
      ext: jpe
    - type: "image/jpeg"
      ext: jpg
    - type: "image/png"
      ext: png
    - type: "text/xml"
      ext: xml

task_schedule:
  reload_settings:
    caption: "Settings.Reload"
    startup: true
    period: 5m
    timeout: 15s
  mailer:
    send_processor:
      caption: "Mailer.SendProcessor"
      ready_timeout: 60s
      start_read_delay: 5s
      read_period: 2m
      cancel_read_timeout: 5s
      handler_timeout: 30s
      queue_size: 25
      workers_count: 1
    change_from_to_retry:
      caption: "Mailer.ChangeFromToRetry"
      # startup: false
      period: 600s
      timeout: 60s
    clean_queue:
      caption: "Mailer.CleanQueue"
      # startup: false
      period: 45m
      timeout: 60s
    send_retry_attempts: 3
    send_delay_correction: 15s
    change_queue_limit: 100
    change_retry_timeout: 60s
    change_retry_delayed: 0s
    clean_queue_limit: 100
  notifier:
    send_processor:
      caption: "Notifier.SendProcessor"
      ready_timeout: 60s
      start_read_delay: 0s
      read_period: 2m
      cancel_read_timeout: 5s
      handler_timeout: 30s
      queue_size: 25
      workers_count: 1
    change_from_to_retry:
      caption: "Notifier.ChangeFromToRetry"
      # startup: false
      period: 600s
      timeout: 60s
    clean_queue:
      caption: "Notifier.CleanQueue"
      # startup: false
      period: 45m
      timeout: 60s
    send_retry_attempts: 3
    change_queue_limit: 100
    change_retry_timeout: 60s
    change_retry_delayed: 30s
    clean_queue_limit: 100